### ISSUE TITLE
Evil Sellers can extort money from buyers

### ISSUE THREAD

**Issue by SmallAndSoft** [AlejandroDiaz666/mad-stores#2]
An evil seller could trick buyer into MAD escrow and say straight away that no goods will be shipped, further demanding up to 50% of price in his favor in resolution. The buyer stands to loose more than seller.

**Comment by AlejandroDiaz666** [comment]
Although the MAD Escrow system is far from 100% fool-proof, this particular scenario is not realistic. The reason is that the buyer is able to cancel the escrow (and recover all his deposited funds) up until the time that the seller "approves." After the seller approves the escrow is locked, and the seller cannot modify the price. The only "resolution" at that time is that the buyer either releases the escrow, which pays the seller the full price, or burns the escrow, in which case the seller gets nothing. The decision is completely in the hands of the buyer.

The only way this could play out is if the seller says "I'm not going to ship you the item, but go ahead and release the escrow so that you don't lose your 50% bond". The assumption I have made is that most buyers would tell the seller to "go climb a tree" and would prefer lose their bond rather than be taken advantage of. At any rate, the seller has no way of knowing if a buyer would or wouldn't, and therefore he would be risking his own bond.

An evil seller would also undoubtedly be rated very poorly. Sellers would work hard to build their reputations, and would want to protect their reputations. Many buyers would not purchase at all from a seller who has not completed many escrows. And those that would deal with a brand-new seller would probably be pretty steely about not tolerating an evil seller. And lastly, even if a buyer were to capitulate to an evil seller by releasing the escrow, he could leave a rating of zero. This would warn future buyers to beware.

**Comment by SmallAndSoft** [comment]
Reputation system works outside MAD escrow and is subject to it's own limitations. #1 explains why sellers may want to rotate their identities along with reputation. The anonymous nature of buyers and sellers makes forging seller history very easy. I believe the issue should not be closed so hastily.
